#
# CSE186 Assignment 7 Backend
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 7 Backend
  version: 0.2.0
  title: CSE186 Assignment 7 Backend

servers:
  - url: http://localhost:3010/api/v0

paths:
  /mailbox:
    get:
      summary: Returns a list of mailboxes
      responses:
        '200':
          description: A list of mailbox names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
