openapi: '3.0.3'

info:
  description: CSE186 Assignment 7 Backend
  version: 0.2.0
  title: CSE186 Assignment 7 Backend

servers:
  - url: http://localhost:3010/api/v0

paths:
  /mailbox:
    get:
      summary: Returns a list of mailboxes
      responses:
        '200':
          description: A list of mailbox names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /mail:
    get:
      summary: Returns a list of emails for a given mailbox
      parameters:
        - in: query
          name: mailbox
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of emails
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    from:
                      type: object
                    to:
                      type: object
                    subject:
                      type: string
                    received:
                      type: string
        '400':
          description: Bad request

  /mail/{id}:
    get:
      summary: Get a full email by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A complete email object
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Email not found
    put:
      summary: Move an email to a different mailbox
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: mailbox
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful move
        '400':
          description: Invalid request
        '403':
          description: Forbidden
        '404':
          description: Not found